'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '@/shared/api/client';
import { READ_QUERY_REFETCH } from '@/shared/api/query-options';
import { clampPageSize } from '@/shared/lib/pagination';
import {
  OperatorInvitationSchema,
  OperatorInvitationPageSchema,
  type OperatorInvitation,
  type OperatorInvitationPage,
  type InviteOperatorInput,
  type InvitationStatus,
} from '../api/invitation-types';
import { invitationsKey, invalidateInvitations } from '../api/operators-keys';

/**
 * Client hooks for the operator-invitation surface (TASK-MONO-772 S5 —
 * console contract § 2.4.3 rows 11–14). Every call goes to the same-origin
 * `/api/operator-invitations/**` proxy, which attaches the operator token +
 * active tenant + the per-endpoint header matrix server-side.
 *
 * Refetch posture («optimistic-safe»): NO optimistic cache writes. A mutation
 * settles, THEN the list is invalidated and refetched from the producer —
 * cancel/resend invalidate on SETTLE (success OR error), because the two
 * «list is stale» answers (`409 OPERATOR_INVITATION_NOT_PENDING`,
 * `404 OPERATOR_INVITATION_NOT_FOUND`) mean another actor already moved the
 * row, and the contract says «refresh the list».
 *
 * The reason is never fabricated here — it is required input from the
 * confirm dialog. The idempotency key (invite only) is generated once per
 * confirmed invite by the screen and reused only on a retry of THAT invite.
 */

export interface InvitationsQuery {
  status: InvitationStatus;
  page: number;
  size: number;
}

async function queryInvitations(
  tenantId: string,
  q: InvitationsQuery,
): Promise<OperatorInvitationPage> {
  const qs = new URLSearchParams();
  qs.set('tenantId', tenantId);
  qs.set('status', q.status);
  qs.set('page', String(Math.max(0, q.page)));
  qs.set('size', String(clampPageSize(q.size, 20, 100)));
  const raw = await apiClient.get<unknown>(
    `/api/operator-invitations?${qs.toString()}`,
  );
  return OperatorInvitationPageSchema.parse(raw);
}

/**
 * Pending invitations of `tenantId` (the ACTIVE tenant). Disabled when no
 * tenant is known — the call is never sent with an empty scope.
 */
export function useOperatorInvitations(
  tenantId: string | null,
  q: InvitationsQuery,
) {
  return useQuery({
    queryKey: invitationsKey(tenantId, q.status, q.page, q.size),
    queryFn: () => queryInvitations(tenantId as string, q),
    enabled: tenantId !== null && tenantId !== '',
    ...READ_QUERY_REFETCH,
  });
}

// --- mutation: invite (reason + idempotency key) ---------------------------

interface InviteArgs {
  input: InviteOperatorInput;
  reason: string;
  /** Stable per the confirmed invite (generated by the screen). */
  idempotencyKey: string;
}

export function useInviteOperator() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      input,
      reason,
      idempotencyKey,
    }: InviteArgs): Promise<OperatorInvitation> => {
      const raw = await apiClient.post<unknown>('/api/operator-invitations', {
        ...input,
        reason,
        idempotencyKey,
      });
      return OperatorInvitationSchema.parse(raw);
    },
    // `201` is a success even when the mail failed (`delivery.status =
    // FAILED_*`) — the invitation exists and must show up in the list.
    onSuccess: () => invalidateInvitations(qc),
  });
}

// --- mutation: cancel / resend (reason ONLY — NO idempotency key) ----------

interface InvitationReasonArgs {
  invitationId: string;
  reason: string;
}

export function useCancelInvitation() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      invitationId,
      reason,
    }: InvitationReasonArgs): Promise<OperatorInvitation> => {
      const raw = await apiClient.post<unknown>(
        `/api/operator-invitations/${encodeURIComponent(invitationId)}/cancel`,
        { reason },
      );
      return OperatorInvitationSchema.parse(raw);
    },
    onSettled: () => invalidateInvitations(qc),
  });
}

export function useResendInvitation() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      invitationId,
      reason,
    }: InvitationReasonArgs): Promise<OperatorInvitation> => {
      const raw = await apiClient.post<unknown>(
        `/api/operator-invitations/${encodeURIComponent(invitationId)}/resend`,
        { reason },
      );
      return OperatorInvitationSchema.parse(raw);
    },
    onSettled: () => invalidateInvitations(qc),
  });
}
