apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8086"
  OTEL_SERVICE_NAME: "order-service"
  DB_URL: "jdbc:postgresql://order-postgres.infra.svc.cluster.local:5432/order_db"
