package com.example.scmplatform.procurement.integration;

import com.example.common.id.UuidV7;
import com.example.common.persistence.DataIntegrityViolations;
import com.example.scmplatform.procurement.domain.po.PurchaseOrder;
import com.example.scmplatform.procurement.domain.po.PurchaseOrderLine;
import com.example.scmplatform.procurement.presentation.advice.GlobalExceptionHandler;
import com.example.scmplatform.procurement.presentation.dto.ApiErrorBody;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.math.BigDecimal;
import java.sql.SQLException;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.fail;

/**
 * Reachability IT for the selective {@code DataIntegrityViolation} mapping
 * (TASK-MONO-450). Proves — against a real PostgreSQL (Testcontainers), no
 * mocking — that:
 *
 * <ol>
 *   <li>a real <b>unique</b> constraint violation surfaces SQLSTATE {@code 23505}
 *       through Spring's exception translation into the cause chain, and the
 *       handler maps it to <b>409 CONFLICT</b>; and</li>
 *   <li>a real <b>foreign-key</b> violation surfaces a <em>non</em>-23505 SQLSTATE
 *       ({@code 23503}), so {@link DataIntegrityViolations#isUniqueViolation} returns
 *       {@code false} and the handler maps it to <b>500 INTERNAL_ERROR</b> — the
 *       server defect stays loud instead of being masked as a 409.</li>
 * </ol>
 *
 * <p>The exception is generated by the DB (via {@code saveAndFlush} on the real JPA
 * repositories) and then fed to the real {@link GlobalExceptionHandler}. This is the
 * whole point of the ticket: proving SQLSTATE 23505 reaches the handler through the
 * production Postgres dialect + Spring translation, which a unit test on a hand-built
 * exception cannot establish. The unit-level branch coverage lives in
 * {@code GlobalExceptionHandlerTest}.
 */
@Tag("integration")
@DisplayName("IT: DataIntegrityViolation selective mapping (23505 → 409, else → 500)")
class DataIntegrityViolationIntegrationTest extends AbstractProcurementIntegrationTest {

    private final GlobalExceptionHandler handler = new GlobalExceptionHandler();

    @Test
    @DisplayName("real unique violation (uq_purchase_orders_tenant_po_number) → SQLSTATE 23505 → 409 CONFLICT")
    void uniqueViolationMapsToConflict() {
        // Arrange — commit a PO with a fixed (tenant_id, po_number).
        String poNumber = "PO-DUP-" + UuidV7.randomString().replace("-", "").substring(20).toUpperCase();
        PurchaseOrder first = PurchaseOrder.createDraft(
                UuidV7.randomString(), TENANT_SCM, poNumber, "sup-dup-001", "buyer-dup-001", "USD");
        poJpa.saveAndFlush(first);

        // A second PO reusing the same (tenant_id, po_number) violates the UNIQUE index.
        PurchaseOrder duplicate = PurchaseOrder.createDraft(
                UuidV7.randomString(), TENANT_SCM, poNumber, "sup-dup-002", "buyer-dup-002", "USD");

        // Act — the DB rejects the flush; Spring translates to DataIntegrityViolationException.
        DataIntegrityViolationException ex = null;
        try {
            poJpa.saveAndFlush(duplicate);
            fail("expected a DataIntegrityViolationException from the unique constraint");
        } catch (DataIntegrityViolationException caught) {
            ex = caught;
        }

        // Assert — the SQLSTATE 23505 is really in the cause chain (not inferred from the message).
        assertThat(ex).isNotNull();
        assertThat(sqlStateOf(ex))
                .as("Postgres unique_violation SQLSTATE must reach the handler via the cause chain")
                .isEqualTo("23505");
        assertThat(DataIntegrityViolations.isUniqueViolation(ex)).isTrue();

        // Assert — the real handler maps it to 409 CONFLICT (scm's "must change state first").
        ResponseEntity<ApiErrorBody> response = handler.handleIntegrity(ex);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().code()).isEqualTo("CONFLICT");
    }

    @Test
    @DisplayName("real FK violation (fk_pol_po, non-unique) → non-23505 SQLSTATE → 500 INTERNAL_ERROR")
    void foreignKeyViolationMapsToInternalError() {
        // Arrange — a line pointing at a po_id that does not exist violates fk_pol_po.
        PurchaseOrderLine orphanLine = PurchaseOrderLine.create(
                UuidV7.randomString(),
                "po-does-not-exist-" + UuidV7.randomString(),
                TENANT_SCM,
                1, "sku-fk-001", "sup-sku-fk-001",
                new BigDecimal("1"), new BigDecimal("1.00"));

        // Act — the DB rejects the flush on the FK constraint.
        DataIntegrityViolationException ex = null;
        try {
            lineJpa.saveAndFlush(orphanLine);
            fail("expected a DataIntegrityViolationException from the foreign-key constraint");
        } catch (DataIntegrityViolationException caught) {
            ex = caught;
        }

        // Assert — this is NOT a unique violation, so it must NOT be masked as a 409.
        assertThat(ex).isNotNull();
        assertThat(sqlStateOf(ex))
                .as("a foreign-key violation is SQLSTATE 23503, never 23505")
                .isNotEqualTo("23505");
        assertThat(DataIntegrityViolations.isUniqueViolation(ex)).isFalse();

        // Assert — the real handler maps it to 500 INTERNAL_ERROR (server defect stays loud).
        ResponseEntity<ApiErrorBody> response = handler.handleIntegrity(ex);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR);
        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().code()).isEqualTo("INTERNAL_ERROR");
    }

    /** First non-null SQLSTATE found walking the throwable's cause chain (mirrors the discriminant). */
    private static String sqlStateOf(Throwable t) {
        for (Throwable cause = t; cause != null && cause != cause.getCause(); cause = cause.getCause()) {
            if (cause instanceof SQLException sql && sql.getSQLState() != null) {
                return sql.getSQLState();
            }
        }
        return null;
    }
}
