apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-store-pdb
  namespace: ecommerce
  labels:
    app: web-store
    app.kubernetes.io/part-of: ecommerce
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: web-store
