'use client';

import {
  useEffect,
  useId,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import { Button } from '@/shared/ui/Button';

/**
 * Reason-capture + confirm dialog — the security UX gate for every
 * destructive accounts op (console-integration-contract § 2.4.1 destructive
 * UX / audit-heavy).
 *
 * Invariants:
 *   - `onConfirm` is NOT called until a NON-EMPTY operator reason is entered
 *     (the producer call cannot fire without it — task Failure Scenario
 *     "Destructive action with no confirm/reason gate").
 *   - `requireTypedConfirmation` (gdpr-delete = irreversible): the operator
 *     must additionally type an exact confirmation phrase → effectively a
 *     double-confirm (reason + typed phrase), never a single click.
 *   - Keyboard-operable + WCAG AA: focus moves into the dialog on open,
 *     `Escape` cancels, focus is trapped to the dialog, `role="dialog"` +
 *     `aria-modal` + labelled/!described. axe-clean.
 */
export interface ConfirmActionDialogProps {
  open: boolean;
  title: string;
  /** Short human description of the consequence (rendered as the a11y desc). */
  description: ReactNode;
  confirmLabel: string;
  /** Destructive styling + (when set) the irreversible typed-confirmation. */
  destructive?: boolean;
  /** gdpr-delete: the exact phrase the operator must type to enable confirm. */
  requireTypedConfirmation?: string;
  pending?: boolean;
  /** Inline actionable error from the last attempt (no crash). */
  errorMessage?: string | null;
  onConfirm: (reason: string) => void;
  onCancel: () => void;
}

export function ConfirmActionDialog({
  open,
  title,
  description,
  confirmLabel,
  destructive = false,
  requireTypedConfirmation,
  pending = false,
  errorMessage,
  onConfirm,
  onCancel,
}: ConfirmActionDialogProps) {
  const titleId = useId();
  const descId = useId();
  const reasonId = useId();
  const typedId = useId();
  const dialogRef = useRef<HTMLDivElement>(null);
  const reasonRef = useRef<HTMLTextAreaElement>(null);
  const [reason, setReason] = useState('');
  const [typed, setTyped] = useState('');

  // Reset transient input each time the dialog opens (a fresh user action →
  // a fresh reason; the idempotency key is generated by the caller per
  // confirmed action, never reused across distinct opens).
  useEffect(() => {
    if (open) {
      setReason('');
      setTyped('');
      // Move focus into the dialog (a11y — focus management).
      const t = setTimeout(() => reasonRef.current?.focus(), 0);
      return () => clearTimeout(t);
    }
  }, [open]);

  useEffect(() => {
    if (!open) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        e.preventDefault();
        onCancel();
      }
      if (e.key === 'Tab' && dialogRef.current) {
        const focusable = dialogRef.current.querySelectorAll<HTMLElement>(
          'button, textarea, input, [tabindex]:not([tabindex="-1"])',
        );
        if (focusable.length === 0) return;
        const first = focusable[0];
        const last = focusable[focusable.length - 1];
        if (e.shiftKey && document.activeElement === first) {
          e.preventDefault();
          last.focus();
        } else if (!e.shiftKey && document.activeElement === last) {
          e.preventDefault();
          first.focus();
        }
      }
    }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onCancel]);

  if (!open) return null;

  const reasonOk = reason.trim().length > 0;
  const typedOk =
    !requireTypedConfirmation || typed.trim() === requireTypedConfirmation;
  const canConfirm = reasonOk && typedOk && !pending;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      data-testid="confirm-overlay"
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={descId}
        data-testid="confirm-dialog"
        className="w-full max-w-md rounded-lg border border-border bg-background p-6 shadow-lg"
      >
        <h2
          id={titleId}
          className={
            destructive
              ? 'text-lg font-semibold text-destructive'
              : 'text-lg font-semibold text-foreground'
          }
        >
          {title}
        </h2>
        <div
          id={descId}
          className="mt-2 text-sm text-muted-foreground"
        >
          {description}
        </div>

        <div className="mt-4">
          <label
            htmlFor={reasonId}
            className="block text-sm font-medium text-foreground"
          >
            감사 사유 <span aria-hidden="true">*</span>
            <span className="sr-only">(필수)</span>
          </label>
          <textarea
            id={reasonId}
            ref={reasonRef}
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            required
            aria-required="true"
            rows={3}
            data-testid="confirm-reason"
            className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"
            placeholder="이 운영 작업의 사유를 입력하세요 (감사 기록에 남습니다)"
          />
          {!reasonOk && (
            <p
              className="mt-1 text-xs text-muted-foreground"
              data-testid="reason-required-hint"
            >
              사유를 입력해야 작업을 진행할 수 있습니다.
            </p>
          )}
        </div>

        {requireTypedConfirmation && (
          <div className="mt-4">
            <label
              htmlFor={typedId}
              className="block text-sm font-medium text-foreground"
            >
              되돌릴 수 없는 작업입니다. 계속하려면{' '}
              <code className="rounded bg-muted px-1">
                {requireTypedConfirmation}
              </code>{' '}
              를 입력하세요.
            </label>
            <input
              id={typedId}
              type="text"
              value={typed}
              onChange={(e) => setTyped(e.target.value)}
              data-testid="confirm-typed"
              autoComplete="off"
              className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-destructive"
            />
          </div>
        )}

        {errorMessage && (
          <p
            role="alert"
            data-testid="confirm-error"
            className="mt-4 rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive"
          >
            {errorMessage}
          </p>
        )}

        <div className="mt-6 flex justify-end gap-3">
          <Button
            variant="secondary"
            onClick={onCancel}
            disabled={pending}
            data-testid="confirm-cancel"
          >
            취소
          </Button>
          <Button
            variant={destructive ? 'primary' : 'primary'}
            onClick={() => canConfirm && onConfirm(reason.trim())}
            disabled={!canConfirm}
            data-testid="confirm-submit"
            className={
              destructive
                ? 'bg-destructive text-destructive-foreground hover:opacity-90'
                : undefined
            }
          >
            {pending ? '처리 중…' : confirmLabel}
          </Button>
        </div>
      </div>
    </div>
  );
}
