'use client';

import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { ConfirmDialog } from '@/shared/ui/ConfirmDialog';
import { ConfirmActionDialogBody } from './ConfirmActionDialogBody';

/**
 * Reason-capture + confirm dialog — the security UX gate for every
 * destructive accounts op (console-integration-contract § 2.4.1 destructive
 * UX / audit-heavy).
 *
 * The generic name is deliberate: this one dialog serves several distinct
 * account actions (bulk lock, GDPR delete …), so it is NOT named after a
 * single domain noun.
 *
 * Invariants:
 *   - `onConfirm` is NOT called until a NON-EMPTY operator reason is entered
 *     (the producer call cannot fire without it — task Failure Scenario
 *     "Destructive action with no confirm/reason gate").
 *   - `requireTypedConfirmation` (gdpr-delete = irreversible): the operator
 *     must additionally type an exact confirmation phrase → effectively a
 *     double-confirm (reason + typed phrase), never a single click.
 *   - Keyboard-operable + WCAG AA: focus moves into the dialog on open (the
 *     reason textarea — passed as the primitive's `initialFocusRef`),
 *     `Escape` cancels, focus is trapped to the dialog, `role="dialog"` +
 *     `aria-modal` + labelled/described. axe-clean.
 *
 * Container / presentational (TASK-PC-FE-210, re-based in TASK-PC-FE-262):
 * this container keeps ALL state (reason / typed), the open-reset effect and
 * the `reasonRef`; the shell (overlay, `role="dialog"` frame, ARIA, Escape,
 * focus trap, error banner, footer) is delegated to the shared
 * `shared/ui/ConfirmDialog` primitive, and the two domain fields render in the
 * prop-driven {@link ConfirmActionDialogBody} as that primitive's `children`.
 * The public prop API is UNCHANGED, so no caller changes.
 */
export interface ConfirmActionDialogProps {
  open: boolean;
  title: string;
  /** Short human description of the consequence (rendered as the a11y desc). */
  description: ReactNode;
  confirmLabel: string;
  /** Destructive styling + (when set) the irreversible typed-confirmation. */
  destructive?: boolean;
  /** gdpr-delete: the exact phrase the operator must type to enable confirm. */
  requireTypedConfirmation?: string;
  pending?: boolean;
  /** Inline actionable error from the last attempt (no crash). */
  errorMessage?: string | null;
  onConfirm: (reason: string) => void;
  onCancel: () => void;
}

export function ConfirmActionDialog({
  open,
  title,
  description,
  confirmLabel,
  destructive = false,
  requireTypedConfirmation,
  pending = false,
  errorMessage,
  onConfirm,
  onCancel,
}: ConfirmActionDialogProps) {
  const reasonId = useId();
  const typedId = useId();
  const reasonRef = useRef<HTMLTextAreaElement>(null);
  const [reason, setReason] = useState('');
  const [typed, setTyped] = useState('');

  // Reset transient input each time the dialog opens (a fresh user action →
  // a fresh reason; the idempotency key is generated by the caller per
  // confirmed action, never reused across distinct opens). Focus-into-dialog
  // is the shared primitive's job (`initialFocusRef` = the reason textarea).
  useEffect(() => {
    if (open) {
      setReason('');
      setTyped('');
    }
  }, [open]);

  const reasonOk = reason.trim().length > 0;
  const typedOk =
    !requireTypedConfirmation || typed.trim() === requireTypedConfirmation;
  const canConfirm = reasonOk && typedOk && !pending;

  return (
    <ConfirmDialog
      open={open}
      title={title}
      description={description}
      confirmLabel={confirmLabel}
      destructive={destructive}
      pending={pending}
      confirmDisabled={!reasonOk || !typedOk}
      errorMessage={errorMessage}
      dialogTestId="confirm-dialog"
      overlayTestId="confirm-overlay"
      cancelTestId="confirm-cancel"
      confirmTestId="confirm-submit"
      errorTestId="confirm-error"
      initialFocusRef={reasonRef}
      onConfirm={() => canConfirm && onConfirm(reason.trim())}
      onCancel={onCancel}
    >
      <ConfirmActionDialogBody
        requireTypedConfirmation={requireTypedConfirmation}
        reasonId={reasonId}
        typedId={typedId}
        reasonRef={reasonRef}
        reason={reason}
        onReasonChange={setReason}
        typed={typed}
        onTypedChange={setTyped}
        reasonOk={reasonOk}
      />
    </ConfirmDialog>
  );
}
