'use client';

import {
  useEffect,
  useId,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import { ConfirmActionDialogBody } from './ConfirmActionDialogBody';

/**
 * Reason-capture + confirm dialog — the security UX gate for every
 * destructive accounts op (console-integration-contract § 2.4.1 destructive
 * UX / audit-heavy).
 *
 * Invariants:
 *   - `onConfirm` is NOT called until a NON-EMPTY operator reason is entered
 *     (the producer call cannot fire without it — task Failure Scenario
 *     "Destructive action with no confirm/reason gate").
 *   - `requireTypedConfirmation` (gdpr-delete = irreversible): the operator
 *     must additionally type an exact confirmation phrase → effectively a
 *     double-confirm (reason + typed phrase), never a single click.
 *   - Keyboard-operable + WCAG AA: focus moves into the dialog on open,
 *     `Escape` cancels, focus is trapped to the dialog, `role="dialog"` +
 *     `aria-modal` + labelled/!described. axe-clean.
 *
 * Container / presentational (TASK-PC-FE-210): this container keeps ALL state
 * (reason / typed), the open-reset + auto-focus effect, the Escape / focus-trap
 * key handler, and both `dialogRef` / `reasonRef` + the overlay/`role="dialog"`
 * frame; the title / fields / error / footer render in the prop-driven
 * {@link ConfirmActionDialogBody} inside that same dialog div (so the
 * `querySelectorAll` focus-trap + the ref auto-focus are unchanged).
 */
export interface ConfirmActionDialogProps {
  open: boolean;
  title: string;
  /** Short human description of the consequence (rendered as the a11y desc). */
  description: ReactNode;
  confirmLabel: string;
  /** Destructive styling + (when set) the irreversible typed-confirmation. */
  destructive?: boolean;
  /** gdpr-delete: the exact phrase the operator must type to enable confirm. */
  requireTypedConfirmation?: string;
  pending?: boolean;
  /** Inline actionable error from the last attempt (no crash). */
  errorMessage?: string | null;
  onConfirm: (reason: string) => void;
  onCancel: () => void;
}

export function ConfirmActionDialog({
  open,
  title,
  description,
  confirmLabel,
  destructive = false,
  requireTypedConfirmation,
  pending = false,
  errorMessage,
  onConfirm,
  onCancel,
}: ConfirmActionDialogProps) {
  const titleId = useId();
  const descId = useId();
  const reasonId = useId();
  const typedId = useId();
  const dialogRef = useRef<HTMLDivElement>(null);
  const reasonRef = useRef<HTMLTextAreaElement>(null);
  const [reason, setReason] = useState('');
  const [typed, setTyped] = useState('');

  // Reset transient input each time the dialog opens (a fresh user action →
  // a fresh reason; the idempotency key is generated by the caller per
  // confirmed action, never reused across distinct opens).
  useEffect(() => {
    if (open) {
      setReason('');
      setTyped('');
      // Move focus into the dialog (a11y — focus management).
      const t = setTimeout(() => reasonRef.current?.focus(), 0);
      return () => clearTimeout(t);
    }
  }, [open]);

  useEffect(() => {
    if (!open) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        e.preventDefault();
        onCancel();
      }
      if (e.key === 'Tab' && dialogRef.current) {
        const focusable = dialogRef.current.querySelectorAll<HTMLElement>(
          'button, textarea, input, [tabindex]:not([tabindex="-1"])',
        );
        if (focusable.length === 0) return;
        const first = focusable[0];
        const last = focusable[focusable.length - 1];
        if (e.shiftKey && document.activeElement === first) {
          e.preventDefault();
          last.focus();
        } else if (!e.shiftKey && document.activeElement === last) {
          e.preventDefault();
          first.focus();
        }
      }
    }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onCancel]);

  if (!open) return null;

  const reasonOk = reason.trim().length > 0;
  const typedOk =
    !requireTypedConfirmation || typed.trim() === requireTypedConfirmation;
  const canConfirm = reasonOk && typedOk && !pending;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      data-testid="confirm-overlay"
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={descId}
        data-testid="confirm-dialog"
        className="w-full max-w-md rounded-lg border border-border bg-background p-6 shadow-lg"
      >
        <ConfirmActionDialogBody
          title={title}
          description={description}
          destructive={destructive}
          confirmLabel={confirmLabel}
          requireTypedConfirmation={requireTypedConfirmation}
          pending={pending}
          errorMessage={errorMessage}
          titleId={titleId}
          descId={descId}
          reasonId={reasonId}
          typedId={typedId}
          reasonRef={reasonRef}
          reason={reason}
          onReasonChange={setReason}
          typed={typed}
          onTypedChange={setTyped}
          reasonOk={reasonOk}
          canConfirm={canConfirm}
          onConfirm={() => canConfirm && onConfirm(reason.trim())}
          onCancel={onCancel}
        />
      </div>
    </div>
  );
}
