apiVersion: v1
kind: ConfigMap
metadata:
  name: batch-worker-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8088"
  OTEL_SERVICE_NAME: "batch-worker"
  DB_URL: "jdbc:postgresql://batch-postgres.infra.svc.cluster.local:5432/batch_db"
