apiVersion: v1
kind: Service
metadata:
  name: web-store
  namespace: ecommerce
  labels:
    app: web-store
spec:
  type: ClusterIP
  selector:
    app: web-store
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
