'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '@/shared/api/client';
import { READ_QUERY_REFETCH } from '@/shared/api/query-options';
import {
  DepartmentListResponseSchema,
  type DepartmentListResponse,
  DepartmentSchema,
  type Department,
  type ErpListQueryParams,
  type ErpDetailQueryParams,
  type CreateDepartmentInput,
  type UpdateDepartmentInput,
  type MoveDepartmentParentInput,
} from '../../api/types';
import {
  ERP_KEY,
  departmentDetailKey,
  departmentsListKey,
} from '../../api/erp-keys';
import { clampSize, buildListQs, buildDetailQs, useThreadedAsOf } from '../use-erp-shared';

/**
 * erp-ops masters — departments hooks (TASK-PC-FE-107 split of the former
 * `use-erp-masters.ts` god-file; behavior-preserving, re-exported verbatim
 * through the `use-erp-masters` barrel → the `use-erp-ops` public barrel).
 * List + detail reads + the department WRITE PILOT mutations
 * (create / update / retire / move-parent — TASK-PC-FE-046 / § 2.4.8).
 */

// ---------------------------------------------------------------------------
// departments — list + detail
// ---------------------------------------------------------------------------

async function fetchDepartmentsList(
  params: ErpListQueryParams,
): Promise<DepartmentListResponse> {
  const raw = await apiClient.get<unknown>(
    `/api/erp/masterdata/departments?${buildListQs(params)}`,
  );
  return DepartmentListResponseSchema.parse(raw);
}

export function useDepartments(
  paramsIn: ErpListQueryParams = {},
  initial?: DepartmentListResponse,
) {
  const asOf = useThreadedAsOf(paramsIn.asOf);
  const params: ErpListQueryParams = { ...paramsIn, asOf };
  const seeded =
    initial !== undefined &&
    (params.page ?? 0) === 0 &&
    !params.filters &&
    params.active === undefined;
  return useQuery({
    queryKey: departmentsListKey(
      asOf,
      params.page ?? 0,
      clampSize(params.size),
      params.filters,
    ),
    queryFn: () => fetchDepartmentsList(params),
    initialData: seeded ? initial : undefined,
    staleTime: seeded ? 15_000 : 0,
    refetchOnMount: seeded ? false : true,
    ...READ_QUERY_REFETCH,
    retry: false,
  });
}

async function fetchDepartmentDetail(
  id: string,
  params: ErpDetailQueryParams,
): Promise<Department> {
  const raw = await apiClient.get<unknown>(
    `/api/erp/masterdata/departments/${encodeURIComponent(id)}${buildDetailQs(params)}`,
  );
  return DepartmentSchema.parse(raw);
}

export function useDepartment(id: string | null, asOfExplicit?: string | null) {
  const asOf = useThreadedAsOf(asOfExplicit);
  return useQuery({
    queryKey: departmentDetailKey(id ?? '', asOf),
    queryFn: () => fetchDepartmentDetail(id as string, { asOf }),
    enabled: Boolean(id && id.trim()),
    staleTime: 15_000,
    refetchOnMount: false,
    ...READ_QUERY_REFETCH,
    retry: false,
  });
}

// ---------------------------------------------------------------------------
// Department WRITE PILOT mutations (TASK-PC-FE-046 / § 2.4.8 *Department
// write binding (PILOT)*). The ONLY erp mutation hooks at pilot time — the
// other four masters stay read-only until TASK-PC-FE-048. Each goes to a
// same-origin POST proxy route (the typed client has only get/post; the route
// forwards with the correct UPSTREAM method — POST create / PATCH update /
// POST retire / POST move-parent). The `Idempotency-Key` is generated by the
// calling component per attempt (the operators `crypto.randomUUID()` pattern)
// and threaded through the body → the proxy → the api-client header. On
// success every department list/detail query is invalidated by prefix (any
// asOf / page).
// ---------------------------------------------------------------------------

function invalidateDepartments(qc: ReturnType<typeof useQueryClient>) {
  qc.invalidateQueries({ queryKey: [ERP_KEY, 'departments'] });
}

export interface CreateDepartmentArgs {
  input: CreateDepartmentInput;
  idempotencyKey: string;
}

export function useCreateDepartment() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ input, idempotencyKey }: CreateDepartmentArgs) => {
      const raw = await apiClient.post<unknown>(
        '/api/erp/masterdata/departments',
        { ...input, idempotencyKey },
      );
      return DepartmentSchema.parse(raw);
    },
    onSuccess: () => invalidateDepartments(qc),
  });
}

export interface UpdateDepartmentArgs {
  id: string;
  input: UpdateDepartmentInput;
  idempotencyKey: string;
}

export function useUpdateDepartment() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, input, idempotencyKey }: UpdateDepartmentArgs) => {
      const raw = await apiClient.post<unknown>(
        `/api/erp/masterdata/departments/${encodeURIComponent(id)}`,
        { ...input, idempotencyKey },
      );
      return DepartmentSchema.parse(raw);
    },
    onSuccess: () => invalidateDepartments(qc),
  });
}

export interface RetireDepartmentArgs {
  id: string;
  reason: string;
  idempotencyKey: string;
}

export function useRetireDepartment() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, reason, idempotencyKey }: RetireDepartmentArgs) => {
      const raw = await apiClient.post<unknown>(
        `/api/erp/masterdata/departments/${encodeURIComponent(id)}/retire`,
        { reason, idempotencyKey },
      );
      return DepartmentSchema.parse(raw);
    },
    onSuccess: () => invalidateDepartments(qc),
  });
}

export interface MoveDepartmentParentArgs {
  id: string;
  input: MoveDepartmentParentInput;
  idempotencyKey: string;
}

export function useMoveDepartmentParent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      id,
      input,
      idempotencyKey,
    }: MoveDepartmentParentArgs) => {
      const raw = await apiClient.post<unknown>(
        `/api/erp/masterdata/departments/${encodeURIComponent(id)}/move-parent`,
        { ...input, idempotencyKey },
      );
      return DepartmentSchema.parse(raw);
    },
    onSuccess: () => invalidateDepartments(qc),
  });
}
