'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '@/shared/api/client';
import { READ_QUERY_REFETCH } from '@/shared/api/query-options';
import { clampPageSize } from '@/shared/lib/pagination';
import {
  DelegationListResponseSchema,
  type DelegationListResponse,
  type CreateDelegationInput,
} from '../api/delegation-types';
import {
  DelegationFactListResponseSchema,
  type DelegationFactListResponse,
  type DelegationFact,
  type DelegationFactListQueryParams,
  ERP_DEFAULT_PAGE_SIZE,
  ERP_MAX_PAGE_SIZE,
} from '../api/types';
import {
  ERP_KEY,
  DELEGATION_PREFIX,
  delegationListKey,
  delegationFactsListKey,
  delegationFactDetailKey,
} from '../api/erp-keys';
import { clampSize } from './use-erp-shared';

// ---------------------------------------------------------------------------
// delegation grant management (TASK-PC-FE-054 — PC-FE-053 follow-up).
// Read query (list) + 2 mutations (create + revoke). Every call goes to the
// same-origin `/api/erp/approval/delegations/**` proxy; the proxy attaches
// the domain-facing IAM OIDC token server-side. On a successful mutation the
// entire `delegation` prefix is invalidated so both DELEGATOR + DELEGATE
// lists refetch. The Idempotency-Key is generated by the calling component
// per attempt (same pattern as approval mutations). The delegation reason
// rides in the body (NOT X-Operator-Reason — the delegation surface does not
// define an operator-reason audit header).
// ---------------------------------------------------------------------------

function invalidateDelegations(qc: ReturnType<typeof useQueryClient>) {
  qc.invalidateQueries({ queryKey: [ERP_KEY, DELEGATION_PREFIX] });
}

async function fetchDelegationList(
  role: 'DELEGATOR' | 'DELEGATE' | undefined,
): Promise<DelegationListResponse> {
  const qs = role ? `?role=${encodeURIComponent(role)}` : '';
  const raw = await apiClient.get<unknown>(
    `/api/erp/approval/delegations${qs}`,
  );
  return DelegationListResponseSchema.parse(raw);
}

export function useDelegations(role?: 'DELEGATOR' | 'DELEGATE') {
  return useQuery({
    queryKey: delegationListKey(role),
    queryFn: () => fetchDelegationList(role),
    refetchOnMount: true,
    ...READ_QUERY_REFETCH,
    retry: false,
  });
}

export interface CreateDelegationArgs {
  input: CreateDelegationInput;
  idempotencyKey: string;
}

export function useCreateDelegation() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ input, idempotencyKey }: CreateDelegationArgs) => {
      const raw = await apiClient.post<unknown>(
        '/api/erp/approval/delegations',
        {
          delegateId: input.delegateId,
          validFrom: input.validFrom,
          ...(input.validTo ? { validTo: input.validTo } : {}),
          ...(input.reason ? { reason: input.reason } : {}),
          idempotencyKey,
        },
      );
      return raw;
    },
    onSuccess: () => invalidateDelegations(qc),
  });
}

export interface RevokeDelegationArgs {
  id: string;
  reason: string;
  idempotencyKey: string;
}

export function useRevokeDelegation() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, reason, idempotencyKey }: RevokeDelegationArgs) => {
      const raw = await apiClient.post<unknown>(
        `/api/erp/approval/delegations/${encodeURIComponent(id)}/revoke`,
        { reason, idempotencyKey },
      );
      return raw;
    },
    onSuccess: () => invalidateDelegations(qc),
  });
}

// ---------------------------------------------------------------------------
// read-model — delegation facts (TASK-PC-FE-055, READ-ONLY)
//   GET /api/erp/read-model/delegations
//   GET /api/erp/read-model/delegations/{grantId}
// No mutation hook exists (E5 — read-model has no write surface).
// ---------------------------------------------------------------------------

async function fetchDelegationFactsList(
  params: DelegationFactListQueryParams,
): Promise<DelegationFactListResponse> {
  const qs = new URLSearchParams();
  if (params.delegatorId) qs.set('delegatorId', params.delegatorId);
  if (params.delegateId) qs.set('delegateId', params.delegateId);
  if (params.status) qs.set('status', params.status);
  if (params.activeAt) qs.set('activeAt', params.activeAt);
  qs.set('page', String(Math.max(0, params.page ?? 0)));
  qs.set('size', String(clampPageSize(params.size, ERP_DEFAULT_PAGE_SIZE, ERP_MAX_PAGE_SIZE)));
  const raw = await apiClient.get<unknown>(
    `/api/erp/read-model/delegations?${qs.toString()}`,
  );
  return DelegationFactListResponseSchema.parse(raw);
}

export function useDelegationFacts(
  paramsIn: DelegationFactListQueryParams = {},
  initial?: DelegationFactListResponse,
) {
  const params = paramsIn;
  const seeded =
    initial !== undefined &&
    (params.page ?? 0) === 0 &&
    !params.delegatorId &&
    !params.delegateId &&
    !params.status &&
    !params.activeAt;
  return useQuery({
    queryKey: delegationFactsListKey(
      params.delegatorId,
      params.delegateId,
      params.status,
      params.activeAt,
      params.page ?? 0,
      clampSize(params.size),
    ),
    queryFn: () => fetchDelegationFactsList(params),
    initialData: seeded ? initial : undefined,
    staleTime: seeded ? 15_000 : 0,
    refetchOnMount: seeded ? false : true,
    ...READ_QUERY_REFETCH,
    retry: false,
  });
}

async function fetchDelegationFactDetail(grantId: string): Promise<DelegationFact> {
  const raw = await apiClient.get<unknown>(
    `/api/erp/read-model/delegations/${encodeURIComponent(grantId)}`,
  );
  const env = (raw ?? {}) as { data?: unknown };
  return DelegationFactListResponseSchema.shape.data.element.parse(env.data ?? raw);
}

export function useDelegationFact(grantId: string | null) {
  return useQuery({
    queryKey: delegationFactDetailKey(grantId ?? ''),
    queryFn: () => fetchDelegationFactDetail(grantId as string),
    enabled: Boolean(grantId && grantId.trim()),
    staleTime: 0,
    refetchOnMount: true,
    ...READ_QUERY_REFETCH,
    retry: false,
  });
}
