'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '@/shared/api/client';
import { READ_QUERY_REFETCH } from '@/shared/api/query-options';
import {
  ApprovalListResponseSchema,
  type ApprovalListResponse,
  ApprovalRequestSchema,
  type ApprovalRequest,
  type ApprovalListQueryParams,
  type ApprovalInboxQueryParams,
  type CreateApprovalInput,
  APPROVAL_DEFAULT_PAGE_SIZE,
  APPROVAL_MAX_PAGE_SIZE,
} from '../api/approval-types';
import {
  ERP_KEY,
  APPROVAL_PREFIX,
  approvalListKey,
  approvalDetailKey,
  approvalInboxKey,
} from '../api/erp-keys';

// ---------------------------------------------------------------------------
// approval workflow (TASK-PC-FE-051 — ADR-MONO-016 § D3.1 parity slice).
// Read queries (list / detail / inbox) + 5 mutations (create + 4 state-machine
// transitions). Every call goes to the same-origin `/api/erp/approval/**`
// proxy; the proxy attaches the domain-facing IAM OIDC token + Idempotency-Key
// + X-Operator-Reason server-side (the browser never reads a token). On a
// successful mutation the entire `approval` prefix is invalidated so list +
// detail + inbox all refetch (the state machine moved). The Idempotency-Key is
// generated by the calling component per attempt (the masterdata write pattern
// reused) and threaded through the body → the proxy → the api-client header.
// ---------------------------------------------------------------------------

function clampApprovalSize(size?: number): number {
  return Math.min(
    APPROVAL_MAX_PAGE_SIZE,
    Math.max(1, size ?? APPROVAL_DEFAULT_PAGE_SIZE),
  );
}

function invalidateApproval(qc: ReturnType<typeof useQueryClient>) {
  qc.invalidateQueries({ queryKey: [ERP_KEY, APPROVAL_PREFIX] });
}

async function fetchApprovalList(
  params: ApprovalListQueryParams,
): Promise<ApprovalListResponse> {
  const qs = new URLSearchParams();
  if (params.status) qs.set('status', params.status);
  if (params.role) qs.set('role', params.role);
  qs.set('page', String(Math.max(0, params.page ?? 0)));
  qs.set('size', String(clampApprovalSize(params.size)));
  const raw = await apiClient.get<unknown>(
    `/api/erp/approval/requests?${qs.toString()}`,
  );
  return ApprovalListResponseSchema.parse(raw);
}

export function useApprovalRequests(
  paramsIn: ApprovalListQueryParams = {},
  initial?: ApprovalListResponse,
) {
  const params = paramsIn;
  const seeded =
    initial !== undefined &&
    (params.page ?? 0) === 0 &&
    !params.status &&
    !params.role;
  return useQuery({
    queryKey: approvalListKey(
      params.status,
      params.role,
      params.page ?? 0,
      clampApprovalSize(params.size),
    ),
    queryFn: () => fetchApprovalList(params),
    initialData: seeded ? initial : undefined,
    staleTime: seeded ? 15_000 : 0,
    refetchOnMount: seeded ? false : true,
    ...READ_QUERY_REFETCH,
    retry: false,
  });
}

async function fetchApprovalInbox(
  params: ApprovalInboxQueryParams,
): Promise<ApprovalListResponse> {
  const qs = new URLSearchParams();
  qs.set('page', String(Math.max(0, params.page ?? 0)));
  qs.set('size', String(clampApprovalSize(params.size)));
  const raw = await apiClient.get<unknown>(
    `/api/erp/approval/inbox?${qs.toString()}`,
  );
  return ApprovalListResponseSchema.parse(raw);
}

export function useApprovalInbox(
  paramsIn: ApprovalInboxQueryParams = {},
  initial?: ApprovalListResponse,
) {
  const params = paramsIn;
  const seeded = initial !== undefined && (params.page ?? 0) === 0;
  return useQuery({
    queryKey: approvalInboxKey(params.page ?? 0, clampApprovalSize(params.size)),
    queryFn: () => fetchApprovalInbox(params),
    initialData: seeded ? initial : undefined,
    staleTime: seeded ? 15_000 : 0,
    refetchOnMount: seeded ? false : true,
    ...READ_QUERY_REFETCH,
    retry: false,
  });
}

/** Detail / mutation proxy responses are `{ data: <ApprovalRequest> }`. */
function parseApprovalDetail(raw: unknown): ApprovalRequest {
  const env = (raw ?? {}) as { data?: unknown };
  return ApprovalRequestSchema.parse(env.data);
}

async function fetchApprovalDetail(id: string): Promise<ApprovalRequest> {
  const raw = await apiClient.get<unknown>(
    `/api/erp/approval/requests/${encodeURIComponent(id)}`,
  );
  return parseApprovalDetail(raw);
}

export function useApprovalRequest(id: string | null) {
  return useQuery({
    queryKey: approvalDetailKey(id ?? ''),
    queryFn: () => fetchApprovalDetail(id as string),
    enabled: Boolean(id && id.trim()),
    staleTime: 0,
    refetchOnMount: true,
    ...READ_QUERY_REFETCH,
    retry: false,
  });
}

// mutations -----------------------------------------------------------------

export interface CreateApprovalArgs {
  input: CreateApprovalInput;
  idempotencyKey: string;
}

export function useCreateApproval() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ input, idempotencyKey }: CreateApprovalArgs) => {
      const raw = await apiClient.post<unknown>(
        '/api/erp/approval/requests',
        { ...input, idempotencyKey },
      );
      return parseApprovalDetail(raw);
    },
    onSuccess: () => invalidateApproval(qc),
  });
}

/** Shared transition args — `reason` required for reject / withdraw, optional
 *  for approve, absent for submit (the dialog enforces the per-transition
 *  rule; the proxy route is the authoritative guard). */
export interface ApprovalTransitionArgs {
  id: string;
  idempotencyKey: string;
  reason?: string;
}

function useApprovalTransition(transition: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, idempotencyKey, reason }: ApprovalTransitionArgs) => {
      const raw = await apiClient.post<unknown>(
        `/api/erp/approval/requests/${encodeURIComponent(id)}/${transition}`,
        { idempotencyKey, ...(reason ? { reason } : {}) },
      );
      return parseApprovalDetail(raw);
    },
    onSuccess: () => invalidateApproval(qc),
  });
}

export function useSubmitApproval() {
  return useApprovalTransition('submit');
}
export function useApproveApproval() {
  return useApprovalTransition('approve');
}
export function useRejectApproval() {
  return useApprovalTransition('reject');
}
export function useWithdrawApproval() {
  return useApprovalTransition('withdraw');
}
