package com.example.fanplatform.community.testsupport;

import com.example.fanplatform.community.infrastructure.security.ActorContextJwtAuthenticationConverter;
import com.example.fanplatform.community.infrastructure.security.AllowedIssuersValidator;
import com.example.fanplatform.community.infrastructure.security.TenantClaimValidator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.jwk.RSAKey;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.oauth2.core.DelegatingOAuth2TokenValidator;
import org.springframework.security.oauth2.core.OAuth2Error;
import org.springframework.security.oauth2.core.OAuth2TokenValidator;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.security.oauth2.jwt.JwtTimestampValidator;
import org.springframework.security.oauth2.jwt.JwtValidationException;
import org.springframework.security.oauth2.jwt.NimbusJwtDecoder;
import org.springframework.security.oauth2.server.resource.InvalidBearerTokenException;
import org.springframework.security.web.SecurityFilterChain;

import java.io.IOException;
import java.security.interfaces.RSAPublicKey;
import java.time.Instant;
import java.util.List;

/**
 * Slice-test security wiring for community-service controller {@link
 * org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest} tests.
 *
 * <p>Provides a {@link JwtDecoder} that verifies tokens with the local key
 * generated by {@link JwtTestHelper}, plus the same Resource Server
 * filter chain rules as production (issuer allowlist + tenant_id validator +
 * 401/403 envelope shape via {@link
 * com.example.fanplatform.community.infrastructure.security.SecurityConfig}).
 *
 * <p>Mirrors the GAP community-service {@code SliceTestSecurityConfig} pattern.
 */
@TestConfiguration
@EnableWebSecurity
public class SliceTestSecurityConfig {

    private static final ObjectMapper JSON = new ObjectMapper();

    /** Static reference set by the test class before bean construction. */
    private static JwtTestHelper fixture;

    /**
     * Sets the shared fixture before Spring's context is built. Tests should
     * call this in a {@code static} initializer (not {@code @BeforeAll}, which
     * runs after the Spring context has already constructed beans).
     */
    public static void useFixture(JwtTestHelper f) {
        fixture = f;
    }

    public static JwtTestHelper fixture() {
        if (fixture == null) {
            fixture = new JwtTestHelper();
        }
        return fixture;
    }

    @Bean
    public JwtDecoder jwtDecoder() {
        try {
            JwtTestHelper f = fixture();
            // Reflectively pull the public RSA key out of the helper. The helper
            // hides its internal RSAKey to keep its API minimal; we reconstruct
            // it from the JWKS JSON it emits.
            RSAKey jwk = (RSAKey) com.nimbusds.jose.jwk.JWKSet.parse(f.jwksJson()).getKeys().get(0);
            RSAPublicKey publicKey = jwk.toRSAPublicKey();
            NimbusJwtDecoder decoder = NimbusJwtDecoder.withPublicKey(publicKey).build();
            OAuth2TokenValidator<Jwt> validator = new DelegatingOAuth2TokenValidator<>(
                    new JwtTimestampValidator(),
                    new AllowedIssuersValidator(List.of(
                            JwtTestHelper.SAS_ISSUER,
                            JwtTestHelper.LEGACY_ISSUER)),
                    new TenantClaimValidator(JwtTestHelper.DEFAULT_TENANT_ID));
            decoder.setJwtValidator(validator);
            return decoder;
        } catch (java.text.ParseException | JOSEException e) {
            throw new IllegalStateException("Failed to build slice-test JwtDecoder", e);
        }
    }

    @Bean
    public SecurityFilterChain testFilterChain(HttpSecurity http) throws Exception {
        http
                .csrf(AbstractHttpConfigurer::disable)
                .sessionManagement(s -> s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                .authorizeHttpRequests(auth -> auth
                        .requestMatchers("/api/community/**").authenticated()
                        .anyRequest().denyAll())
                .oauth2ResourceServer(rs -> rs
                        .jwt(jwt -> jwt.jwtAuthenticationConverter(
                                new ActorContextJwtAuthenticationConverter()))
                        .authenticationEntryPoint((req, resp, e) ->
                                onAuthenticationFailure(resp, e))
                        .accessDeniedHandler((req, resp, e) ->
                                writeError(resp, HttpStatus.FORBIDDEN.value(),
                                        "PERMISSION_DENIED", "Access denied")));
        return http.build();
    }

    private static void onAuthenticationFailure(HttpServletResponse response,
                                                org.springframework.security.core.AuthenticationException e)
            throws IOException {
        String code = "UNAUTHORIZED";
        int status = HttpStatus.UNAUTHORIZED.value();
        String message = "Authentication required";
        OAuth2Error oauthError = extractOAuth2Error(e);
        if (oauthError != null) {
            if (TenantClaimValidator.ERROR_CODE_TENANT_MISMATCH.equals(oauthError.getErrorCode())) {
                code = "TENANT_FORBIDDEN";
                status = HttpStatus.FORBIDDEN.value();
                message = oauthError.getDescription() != null
                        ? oauthError.getDescription() : "Cross-tenant access denied";
            } else if (oauthError.getDescription() != null) {
                message = oauthError.getDescription();
            }
        }
        writeError(response, status, code, message);
    }

    private static OAuth2Error extractOAuth2Error(Throwable t) {
        Throwable cur = t;
        OAuth2Error fallback = null;
        while (cur != null) {
            if (cur instanceof JwtValidationException jve) {
                for (OAuth2Error err : jve.getErrors()) {
                    if (err != null && err.getErrorCode() != null
                            && !"invalid_token".equals(err.getErrorCode())) {
                        return err;
                    }
                }
            }
            if (cur instanceof InvalidBearerTokenException ibte) {
                OAuth2Error err = ibte.getError();
                if (err != null) fallback = err;
            }
            cur = cur.getCause();
        }
        return fallback;
    }

    private static void writeError(HttpServletResponse response, int status,
                                   String code, String message) throws IOException {
        response.setStatus(status);
        response.setContentType(MediaType.APPLICATION_JSON_VALUE);
        ObjectNode node = JSON.createObjectNode();
        node.put("code", code);
        node.put("message", message);
        node.put("timestamp", Instant.now().toString());
        try {
            response.getWriter().write(JSON.writeValueAsString(node));
        } catch (JsonProcessingException ex) {
            response.getWriter().write(
                    "{\"code\":\"" + code + "\",\"message\":\"" + message + "\"}");
        }
    }
}
