package com.example.membership.support;

import com.example.membership.infrastructure.security.AllowedIssuersValidator;
import com.example.membership.infrastructure.security.TenantClaimValidator;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.oauth2.core.DelegatingOAuth2TokenValidator;
import org.springframework.security.oauth2.core.OAuth2Error;
import org.springframework.security.oauth2.core.OAuth2TokenValidator;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.security.oauth2.jwt.JwtTimestampValidator;
import org.springframework.security.oauth2.jwt.JwtValidationException;
import org.springframework.security.oauth2.jwt.NimbusJwtDecoder;
import org.springframework.security.oauth2.server.resource.InvalidBearerTokenException;
import org.springframework.security.web.SecurityFilterChain;

import java.io.IOException;
import java.time.Instant;
import java.util.List;

/**
 * membership-service slice-test security wiring (TASK-BE-253).
 *
 * <p>Provides a {@link JwtDecoder} that verifies tokens with the in-process key
 * generated by {@link MembershipJwtTestFixture}, plus a Resource Server filter
 * chain identical in shape to production's.
 */
@TestConfiguration
@EnableWebSecurity
public class SliceTestSecurityConfig {

    private static final ObjectMapper JSON = new ObjectMapper();

    private static MembershipJwtTestFixture fixture;

    /**
     * Sets the shared fixture before Spring's context is built. Tests should call this
     * in a {@code static} initializer (not {@code @BeforeAll}, which runs after the
     * Spring context has already constructed beans).
     */
    public static void useFixture(MembershipJwtTestFixture f) {
        fixture = f;
    }

    /**
     * Returns the active fixture, lazy-initialising one when none was supplied.
     * Tests that need to issue tokens should access this fixture so that signing
     * and verification share keys.
     */
    public static MembershipJwtTestFixture fixture() {
        if (fixture == null) {
            fixture = new MembershipJwtTestFixture();
        }
        return fixture;
    }

    @Bean
    public JwtDecoder jwtDecoder() {
        MembershipJwtTestFixture f = fixture();
        NimbusJwtDecoder decoder = NimbusJwtDecoder.withPublicKey(f.publicKey()).build();
        OAuth2TokenValidator<Jwt> validator = new DelegatingOAuth2TokenValidator<>(
                new JwtTimestampValidator(),
                new AllowedIssuersValidator(List.of(
                        MembershipJwtTestFixture.SAS_ISSUER,
                        MembershipJwtTestFixture.LEGACY_ISSUER)),
                new TenantClaimValidator(MembershipJwtTestFixture.DEFAULT_TENANT_ID));
        decoder.setJwtValidator(validator);
        return decoder;
    }

    @Bean
    public SecurityFilterChain testFilterChain(HttpSecurity http) throws Exception {
        http
                .csrf(AbstractHttpConfigurer::disable)
                .sessionManagement(s -> s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                .authorizeHttpRequests(auth -> auth
                        .requestMatchers("/actuator/**").permitAll()
                        .requestMatchers("/internal/**").authenticated()
                        .requestMatchers("/api/**").authenticated()
                        .anyRequest().denyAll())
                .oauth2ResourceServer(rs -> rs
                        .jwt(jwt -> {})
                        .authenticationEntryPoint((req, resp, e) ->
                                onAuthenticationFailure(resp, e))
                        .accessDeniedHandler((req, resp, e) ->
                                writeError(resp, HttpStatus.FORBIDDEN.value(),
                                        "PERMISSION_DENIED", "Access denied")));
        return http.build();
    }

    private static void onAuthenticationFailure(HttpServletResponse response,
                                                org.springframework.security.core.AuthenticationException e)
            throws IOException {
        String code = "TOKEN_INVALID";
        int status = HttpStatus.UNAUTHORIZED.value();
        String message = "Authentication required";
        OAuth2Error oauthError = extractOAuth2Error(e);
        if (oauthError != null) {
            if (TenantClaimValidator.ERROR_CODE_TENANT_MISMATCH.equals(oauthError.getErrorCode())) {
                code = "TENANT_FORBIDDEN";
                status = HttpStatus.FORBIDDEN.value();
                message = oauthError.getDescription() != null
                        ? oauthError.getDescription() : "Cross-tenant access denied";
            } else if (oauthError.getDescription() != null) {
                message = oauthError.getDescription();
            }
        }
        writeError(response, status, code, message);
    }

    private static OAuth2Error extractOAuth2Error(Throwable t) {
        Throwable cur = t;
        OAuth2Error fallback = null;
        while (cur != null) {
            if (cur instanceof JwtValidationException jve) {
                // Prefer detailed validator errors (tenant_mismatch, invalid_issuer, ...).
                for (OAuth2Error err : jve.getErrors()) {
                    if (err != null && err.getErrorCode() != null
                            && !"invalid_token".equals(err.getErrorCode())) {
                        return err;
                    }
                }
            }
            if (cur instanceof InvalidBearerTokenException ibte) {
                OAuth2Error err = ibte.getError();
                if (err != null) {
                    fallback = err;
                }
            }
            cur = cur.getCause();
        }
        return fallback;
    }

    private static void writeError(HttpServletResponse response, int status,
                                   String code, String message) throws IOException {
        response.setStatus(status);
        response.setContentType(MediaType.APPLICATION_JSON_VALUE);
        ObjectNode node = JSON.createObjectNode();
        node.put("code", code);
        node.put("message", message);
        node.put("timestamp", Instant.now().toString());
        response.getWriter().write(JSON.writeValueAsString(node));
    }
}
