package com.example.community.support;

import com.example.community.infrastructure.config.OAuth2ResourceServerConfig;
import com.example.community.infrastructure.security.ActorContextJwtAuthenticationConverter;
import com.example.security.oauth2.TenantClaimValidator;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.oauth2.core.OAuth2Error;
import org.springframework.security.oauth2.core.OAuth2TokenValidator;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.security.oauth2.jwt.JwtValidationException;
import org.springframework.security.oauth2.jwt.NimbusJwtDecoder;
import org.springframework.security.oauth2.server.resource.InvalidBearerTokenException;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.test.util.ReflectionTestUtils;

import java.io.IOException;
import java.time.Instant;

/**
 * Slice-test security wiring (TASK-BE-253).
 *
 * <p>Provides a {@link JwtDecoder} that verifies tokens with the local key
 * generated by {@link AccountJwtTestFixture}, plus the same Resource Server
 * filter chain rules as production. The decoder is built per-fixture so each
 * test class can supply its own key pair.
 */
@TestConfiguration
@EnableWebSecurity
public class SliceTestSecurityConfig {

    private static final ObjectMapper JSON = new ObjectMapper();

    /** Static reference set by the test class before bean construction. */
    private static AccountJwtTestFixture fixture;

    /**
     * Sets the shared fixture before Spring's context is built. Tests should call this
     * in a {@code static} initializer (not {@code @BeforeAll}, which runs after the
     * Spring context has already constructed beans).
     */
    public static void useFixture(AccountJwtTestFixture f) {
        fixture = f;
    }

    public static AccountJwtTestFixture fixture() {
        if (fixture == null) {
            fixture = new AccountJwtTestFixture();
        }
        return fixture;
    }

    @Bean
    public JwtDecoder jwtDecoder() {
        AccountJwtTestFixture f = fixture();
        // Swapping the KEY is legitimate — there is no auth-service in a slice test, so the
        // decoder verifies against the fixture's local key instead of fetching JWKS.
        NimbusJwtDecoder decoder = NimbusJwtDecoder.withPublicKey(f.publicKey()).build();
        // Swapping the POLICY is not. The validator chain comes from production.
        decoder.setJwtValidator(productionTokenValidator());
        return decoder;
    }

    /**
     * The tenant gate, taken from {@link OAuth2ResourceServerConfig#jwtTokenValidator()} —
     * the bean production actually wires — rather than re-stated here.
     *
     * <p>Until {@code TASK-MONO-390}'s successor this class hand-built its own chain
     * ({@code new AllowedIssuersValidator(...)} + {@code new TenantClaimValidator(...)}).
     * That made it a <strong>second place the policy was written</strong>: relax the real gate
     * and these slice tests stayed green, because they were asserting against a copy of the
     * policy rather than the policy. Same failure as {@code TASK-MONO-355} (wms's wildcard
     * refusal had no coverage) and {@code TASK-MONO-387} (membership's {@code /internal/**}
     * exemption was undefended) — <em>a property nothing can observe is a property nothing is
     * holding.</em>
     *
     * <p>The fix is deliberately <em>not</em> a shared {@code TenantGateTestConfig}: that
     * would be a <strong>third</strong> copy of the policy, which is the thing
     * {@code ADR-MONO-049} exists to remove.
     */
    static OAuth2TokenValidator<Jwt> productionTokenValidator() {
        OAuth2ResourceServerConfig production = new OAuth2ResourceServerConfig();
        ReflectionTestUtils.setField(production, "requiredTenantId",
                AccountJwtTestFixture.DEFAULT_TENANT_ID);
        ReflectionTestUtils.setField(production, "allowedIssuersCsv",
                AccountJwtTestFixture.SAS_ISSUER + "," + AccountJwtTestFixture.LEGACY_ISSUER);
        return production.jwtTokenValidator();
    }

    @Bean
    public SecurityFilterChain testFilterChain(HttpSecurity http) throws Exception {
        http
                .csrf(AbstractHttpConfigurer::disable)
                .sessionManagement(s -> s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                .authorizeHttpRequests(auth -> auth
                        .requestMatchers("/api/community/**").authenticated()
                        .anyRequest().denyAll())
                .oauth2ResourceServer(rs -> rs
                        .jwt(jwt -> jwt.jwtAuthenticationConverter(
                                new ActorContextJwtAuthenticationConverter()))
                        .authenticationEntryPoint((req, resp, e) ->
                                onAuthenticationFailure(resp, e))
                        .accessDeniedHandler((req, resp, e) ->
                                writeError(resp, HttpStatus.FORBIDDEN.value(),
                                        "PERMISSION_DENIED", "Access denied")));
        return http.build();
    }

    private static void onAuthenticationFailure(HttpServletResponse response,
                                                org.springframework.security.core.AuthenticationException e)
            throws IOException {
        String code = "TOKEN_INVALID";
        int status = HttpStatus.UNAUTHORIZED.value();
        String message = "Authentication required";
        OAuth2Error oauthError = extractOAuth2Error(e);
        if (oauthError != null) {
            if (TenantClaimValidator.ERROR_CODE_TENANT_MISMATCH.equals(oauthError.getErrorCode())) {
                code = "TENANT_FORBIDDEN";
                status = HttpStatus.FORBIDDEN.value();
                message = oauthError.getDescription() != null
                        ? oauthError.getDescription() : "Cross-tenant access denied";
            } else if (oauthError.getDescription() != null) {
                message = oauthError.getDescription();
            }
        }
        writeError(response, status, code, message);
    }

    private static OAuth2Error extractOAuth2Error(Throwable t) {
        Throwable cur = t;
        OAuth2Error fallback = null;
        while (cur != null) {
            if (cur instanceof JwtValidationException jve) {
                for (OAuth2Error err : jve.getErrors()) {
                    if (err != null && err.getErrorCode() != null
                            && !"invalid_token".equals(err.getErrorCode())) {
                        return err;
                    }
                }
            }
            if (cur instanceof InvalidBearerTokenException ibte) {
                OAuth2Error err = ibte.getError();
                if (err != null) fallback = err;
            }
            cur = cur.getCause();
        }
        return fallback;
    }

    private static void writeError(HttpServletResponse response, int status,
                                   String code, String message) throws IOException {
        response.setStatus(status);
        response.setContentType(MediaType.APPLICATION_JSON_VALUE);
        ObjectNode node = JSON.createObjectNode();
        node.put("code", code);
        node.put("message", message);
        node.put("timestamp", Instant.now().toString());
        response.getWriter().write(JSON.writeValueAsString(node));
    }
}
