package com.example.fanplatform.artist.testsupport;

import com.example.fanplatform.artist.application.ActorContext;
import com.example.security.servlet.WorkloadIdentityAuthoritiesConverter;
import com.example.security.servlet.actor.ActorContextJwtAuthenticationConverter;
import com.example.security.oauth2.AllowedIssuersValidator;
import com.example.security.oauth2.TenantClaimValidator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.jwk.RSAKey;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.oauth2.core.DelegatingOAuth2TokenValidator;
import org.springframework.security.oauth2.core.OAuth2Error;
import org.springframework.security.oauth2.core.OAuth2TokenValidator;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.security.oauth2.jwt.JwtTimestampValidator;
import org.springframework.security.oauth2.jwt.JwtValidationException;
import org.springframework.security.oauth2.jwt.JwtValidators;
import org.springframework.security.oauth2.jwt.NimbusJwtDecoder;
import org.springframework.security.oauth2.server.resource.InvalidBearerTokenException;
import org.springframework.security.web.SecurityFilterChain;

import java.io.IOException;
import java.security.interfaces.RSAPublicKey;
import java.time.Instant;
import java.util.List;

/**
 * Slice-test security wiring for artist-service controller {@link
 * org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest} tests.
 *
 * <p>Provides a {@link JwtDecoder} that verifies tokens with the local key
 * generated by {@link JwtTestHelper}, plus the same Resource Server filter
 * chain rules as production (issuer allowlist + tenant_id validator + 401/403
 * envelope shape + admin-role enforcement on mutating endpoints) — AND now
 * mirrors production's second, {@code @Order(1)} chain: the workload-identity
 * {@code /internal/**} matcher (TASK-FAN-BE-045 AC-6, ADR-004 A). Both ordered
 * chains are needed here — a single-chain slice config would leave
 * {@code /internal/**} either unreachable or (worse) answered by the end-user
 * chain's rules.
 *
 * <p>The 401/403 error bodies below are restated (not imported from the real
 * {@code SecurityConfig}) because that class's handler methods are
 * package-private to {@code config}; the messages are kept byte-for-byte
 * identical to production's so a slice assertion on message text still means
 * something. The <strong>discriminator itself</strong> —
 * {@link WorkloadIdentityAuthoritiesConverter} — is imported, not restated: the
 * one thing this config must not fork is which scope clears {@code
 * ROLE_INTERNAL}.
 *
 * <p>Mirrors community-service's slice config; differences are the URL prefix
 * matchers and the admin role gate.
 */
@TestConfiguration
@EnableWebSecurity
public class SliceTestSecurityConfig {

    private static final ObjectMapper JSON = new ObjectMapper();

    private static final String[] ADMIN_ROLES = { "ADMIN", "OPERATOR", "SUPER_ADMIN" };

    /** Static reference set by the test class before bean construction. */
    private static JwtTestHelper fixture;

    public static void useFixture(JwtTestHelper f) {
        fixture = f;
    }

    public static JwtTestHelper fixture() {
        if (fixture == null) {
            fixture = new JwtTestHelper();
        }
        return fixture;
    }

    @Bean
    public JwtDecoder jwtDecoder() {
        try {
            JwtTestHelper f = fixture();
            RSAKey jwk = (RSAKey) com.nimbusds.jose.jwk.JWKSet.parse(f.jwksJson()).getKeys().get(0);
            RSAPublicKey publicKey = jwk.toRSAPublicKey();
            NimbusJwtDecoder decoder = NimbusJwtDecoder.withPublicKey(publicKey).build();
            OAuth2TokenValidator<Jwt> validator = new DelegatingOAuth2TokenValidator<>(
                    new JwtTimestampValidator(),
                    new AllowedIssuersValidator(List.of(
                            JwtTestHelper.SAS_ISSUER,
                            JwtTestHelper.LEGACY_ISSUER)),
                    TenantClaimValidator.forTenant(JwtTestHelper.DEFAULT_TENANT_ID)
                        .allowSuperAdminWildcard()
                        .build());
            decoder.setJwtValidator(validator);
            return decoder;
        } catch (java.text.ParseException | JOSEException e) {
            throw new IllegalStateException("Failed to build slice-test JwtDecoder", e);
        }
    }

    /**
     * Workload-identity decoder for {@code /internal/**} slice tests — same local
     * keypair as {@link #jwtDecoder()}, issuer-only validator (no tenant pin),
     * mirroring {@code ServiceLevelOAuth2Config#internalJwtDecoder()}.
     */
    @Bean
    public NimbusJwtDecoder internalJwtDecoder() {
        try {
            JwtTestHelper f = fixture();
            RSAKey jwk = (RSAKey) com.nimbusds.jose.jwk.JWKSet.parse(f.jwksJson()).getKeys().get(0);
            RSAPublicKey publicKey = jwk.toRSAPublicKey();
            NimbusJwtDecoder decoder = NimbusJwtDecoder.withPublicKey(publicKey).build();
            decoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(JwtTestHelper.SAS_ISSUER));
            return decoder;
        } catch (java.text.ParseException | JOSEException e) {
            throw new IllegalStateException("Failed to build slice-test internal JwtDecoder", e);
        }
    }

    /**
     * Order(1): the workload-identity {@code /internal/**} chain, mirroring
     * production {@code SecurityConfig#internalFilterChain}. Uses the real
     * {@link WorkloadIdentityAuthoritiesConverter} — not a restatement — and the real
     * {@code SecurityConfig.REQUIRED_WORKLOAD_SCOPE}, so the scope discriminator a slice
     * test exercises is the genuine one. Restating the scope here instead would let this
     * config keep passing after production's scope changed (TASK-MONO-521).
     */
    @Bean
    @Order(1)
    public SecurityFilterChain internalFilterChain(HttpSecurity http,
                                                    NimbusJwtDecoder internalJwtDecoder) throws Exception {
        http
                .securityMatcher("/internal/**")
                .csrf(AbstractHttpConfigurer::disable)
                .sessionManagement(s -> s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                .authorizeHttpRequests(auth -> auth
                        .anyRequest().hasRole("INTERNAL"))
                .oauth2ResourceServer(rs -> rs
                        .jwt(jwt -> jwt
                                .decoder(internalJwtDecoder)
                                .jwtAuthenticationConverter(new WorkloadIdentityAuthoritiesConverter(
                                        com.example.fanplatform.artist.config.SecurityConfig.REQUIRED_WORKLOAD_SCOPE)))
                        .authenticationEntryPoint((req, resp, e) ->
                                writeError(resp, HttpStatus.UNAUTHORIZED.value(),
                                        "UNAUTHORIZED", "Missing or invalid internal credentials"))
                        .accessDeniedHandler((req, resp, e) ->
                                writeError(resp, HttpStatus.FORBIDDEN.value(),
                                        "FORBIDDEN", "Workload identity required for /internal/**")));
        return http.build();
    }

    @Bean
    @Order(2)
    public SecurityFilterChain testFilterChain(HttpSecurity http, JwtDecoder jwtDecoder) throws Exception {
        http
                .csrf(AbstractHttpConfigurer::disable)
                .sessionManagement(s -> s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                .authorizeHttpRequests(auth -> auth
                        // mutating endpoints — admin only
                        .requestMatchers(HttpMethod.POST,   "/api/artists/**", "/api/artists").hasAnyRole(ADMIN_ROLES)
                        .requestMatchers(HttpMethod.PATCH,  "/api/artists/**").hasAnyRole(ADMIN_ROLES)
                        .requestMatchers(HttpMethod.DELETE, "/api/artists/**").hasAnyRole(ADMIN_ROLES)
                        .requestMatchers(HttpMethod.POST,   "/api/artist-groups/**", "/api/artist-groups").hasAnyRole(ADMIN_ROLES)
                        .requestMatchers(HttpMethod.PATCH,  "/api/artist-groups/**").hasAnyRole(ADMIN_ROLES)
                        .requestMatchers(HttpMethod.DELETE, "/api/artist-groups/**").hasAnyRole(ADMIN_ROLES)
                        .requestMatchers(HttpMethod.POST,   "/api/fandoms/**").hasAnyRole(ADMIN_ROLES)
                        .requestMatchers(HttpMethod.PATCH,  "/api/fandoms/**").hasAnyRole(ADMIN_ROLES)
                        // reads — any authenticated caller
                        .requestMatchers(HttpMethod.GET,    "/api/artists/**", "/api/artists").authenticated()
                        .requestMatchers(HttpMethod.GET,    "/api/artist-groups/**", "/api/artist-groups").authenticated()
                        .requestMatchers(HttpMethod.GET,    "/api/fandoms/**").authenticated()
                        .anyRequest().denyAll())
                .oauth2ResourceServer(rs -> rs
                        .jwt(jwt -> jwt
                                .decoder(jwtDecoder)
                                .jwtAuthenticationConverter(
                                new ActorContextJwtAuthenticationConverter<>(ActorContext::new)))
                        .authenticationEntryPoint((req, resp, e) -> onAuthenticationFailure(resp, e))
                        .accessDeniedHandler((req, resp, e) ->
                                writeError(resp, HttpStatus.FORBIDDEN.value(),
                                        "FORBIDDEN", "Access denied")));
        return http.build();
    }

    private static void onAuthenticationFailure(HttpServletResponse response,
                                                org.springframework.security.core.AuthenticationException e)
            throws IOException {
        String code = "UNAUTHORIZED";
        int status = HttpStatus.UNAUTHORIZED.value();
        String message = "Authentication required";
        OAuth2Error oauthError = extractOAuth2Error(e);
        if (oauthError != null) {
            if (TenantClaimValidator.ERROR_CODE_TENANT_MISMATCH.equals(oauthError.getErrorCode())) {
                code = "TENANT_FORBIDDEN";
                status = HttpStatus.FORBIDDEN.value();
                message = oauthError.getDescription() != null
                        ? oauthError.getDescription() : "Cross-tenant access denied";
            } else if (oauthError.getDescription() != null) {
                message = oauthError.getDescription();
            }
        }
        writeError(response, status, code, message);
    }

    private static OAuth2Error extractOAuth2Error(Throwable t) {
        Throwable cur = t;
        OAuth2Error fallback = null;
        while (cur != null) {
            if (cur instanceof JwtValidationException jve) {
                for (OAuth2Error err : jve.getErrors()) {
                    if (err != null && err.getErrorCode() != null
                            && !"invalid_token".equals(err.getErrorCode())) {
                        return err;
                    }
                }
            }
            if (cur instanceof InvalidBearerTokenException ibte) {
                OAuth2Error err = ibte.getError();
                if (err != null) fallback = err;
            }
            cur = cur.getCause();
        }
        return fallback;
    }

    private static void writeError(HttpServletResponse response, int status,
                                   String code, String message) throws IOException {
        response.setStatus(status);
        response.setContentType(MediaType.APPLICATION_JSON_VALUE);
        ObjectNode node = JSON.createObjectNode();
        node.put("code", code);
        node.put("message", message);
        node.put("timestamp", Instant.now().toString());
        try {
            response.getWriter().write(JSON.writeValueAsString(node));
        } catch (JsonProcessingException ex) {
            response.getWriter().write(
                    "{\"code\":\"" + code + "\",\"message\":\"" + message + "\"}");
        }
    }
}
