-- =============================================================================
-- REPEATABLE (R__) — this file was `V9004__…` until TASK-MONO-524 (2026-08-12).
-- =============================================================================
-- The V9000+ band was chosen (TASK-MONO-207) to stop dev seeds COLLIDING with
-- production version numbers. It did that, and in exchange it poisoned ORDERING:
-- once 9001 is the highest APPLIED version, every later production migration
-- resolves BELOW it = out-of-order, which Flyway rejects by default. auth_db hit
-- exactly that when V0032 landed (2026-08-11) and crash-looped on every host
-- with an existing volume. CI never saw it — CI always starts from a fresh
-- volume, where everything applies in order.
--
-- R__ has neither problem: a repeatable carries NO version (nothing to collide
-- with, nothing to be out of order against) and always runs AFTER every
-- versioned migration — which is the order seed data wants anyway.
--
-- Editing rules this buys, all three load-bearing:
--   · it re-runs whenever its checksum changes ⇒ every statement MUST stay
--     idempotent (this file: INSERT IGNORE only)
--   · repeatables run in DESCRIPTION order ⇒ the `NN_` prefix is the ordering
--     contract between the seeds in this directory. Do not drop it.
--   · never rename an already-applied R__ file — the description is its
--     identity, and a rename reads as "applied migration not resolved locally",
--     which Flyway does NOT tolerate. (A missing VERSIONED file it *does*
--     tolerate, silently, as `future` — that asymmetry is measured in the doc.)
--
-- Rationale in full + how to recover an already-poisoned database:
--   projects/iam-platform/docs/flyway-dev-seed-migrations.md
-- =============================================================================
-- TASK-MONO-221 (ADR-MONO-026 § D7 step 3 — iam admin SOURCE_IP access-condition
-- federation-e2e proof): seed a FIFTH demo customer `ip-pilot-corp`, dedicated to
-- the iam-admin-source-ip-condition spec.
--
-- WHY a dedicated tenant (not acme / globex / initech / umbrella): the proof
-- assigns/unassigns a throwaway operator (`ip-pilot-target`) to/from this tenant
-- AT RUNTIME via the `operator.manage` admin RBAC surface, to exercise the
-- SOURCE_IP access condition (out-of-range X-Forwarded-For → 403; in-range → 201).
-- The federation-e2e suite runs fullyParallel; acme-corp / globex-corp /
-- initech-corp / umbrella-corp are each owned by other specs (entitlement-trust,
-- A↔B switch, plane-separation, tenant-admin-delegation). Binding the proof's
-- assign target to a tenant referenced by NO other spec keeps the assign/unassign
-- cycle fully isolated — it mirrors the MONO-207 initech-corp / MONO-210
-- umbrella-corp discipline exactly.
--
-- WHY no subscription (unlike V9003 umbrella-corp, which seeded [finance] for its
-- billing-admin leg): this proof's only mutation is operator assignment, which
-- does not depend on a tenant_domain_subscription row. The tenant row alone is
-- seeded so the assign target tenant exists at account-service startup.
--
-- WHY migration-dev V9000+ (not seed.sql, not production db/migration): identical
-- rationale to V9001 (globex) / V9002 (initech) / V9003 (umbrella) — dev-only
-- seeds live in the high V9000+ band to never collide with the (gapless)
-- production timeline. `db/migration-dev` is loaded ONLY under the e2e Flyway
-- locations (application-e2e.yml) — ip-pilot-corp never reaches a production DB.
--
-- The matching admin_db side (the throwaway target operator `ip-pilot-target`
-- scoped to ip-pilot-corp) is seeded in
-- tests/federation-hardening-e2e/fixtures/seed.sql § 16.
--
-- INSERT IGNORE keeps it idempotent (mirrors V9001 / V9002 / V9003).

INSERT IGNORE INTO tenants (tenant_id, display_name, tenant_type, status, created_at, updated_at)
VALUES ('ip-pilot-corp', 'IP Pilot Corporation', 'B2B_ENTERPRISE', 'ACTIVE', NOW(6), NOW(6));
