apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8084"
  OTEL_SERVICE_NAME: "user-service"
  DB_URL: "jdbc:postgresql://user-postgres.infra.svc.cluster.local:5432/user_db"
