spring:
  datasource:
    url: jdbc:h2:file:./data/settlement_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  h2:
    console:
      enabled: true
      path: /h2-console

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.KafkaMetricsAutoConfiguration

logging:
  level:
    com.example.settlement: DEBUG
    org.springframework.kafka: OFF
    org.apache.kafka: OFF
